# Generated by Django 3.2.12 on 2023-11-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_productreview_replymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='star_rating',
        ),
    ]
