# Generated by Django 3.2.12 on 2023-11-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_productreview_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
