# Generated by Django 3.2.12 on 2023-11-09 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_coupon_offer_usercouponusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
