# Generated by Django 3.2.12 on 2023-11-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20231109_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
