# Generated by Django 3.2.12 on 2023-11-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCouponUsage',
        ),
    ]
