# Generated by Django 3.2.12 on 2023-11-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_delete_usercouponusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
