# Generated by Django 3.2.12 on 2023-11-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_bal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
