# Generated by Django 3.2.12 on 2023-11-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_product_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
