# Generated by Django 3.2.12 on 2023-11-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=100, null=True),
        ),
    ]
