# Generated by Django 3.2.12 on 2023-11-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_product_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
