# Generated by Django 3.2.12 on 2023-11-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_category_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
